[package]
name = "keyboard_server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-files = "0.6.8"
actix-web = "4.12.0"
pretty_env_logger = "0.5.0"
rustautogui = "2.5.0"
tokio = { version = "1.48.0", features = ["full"] }
